name: Android CI

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Extract WireGuard Version Name
        run: echo "WG_VERSION_NAME=$(grep 'wireguardVersionName' gradle.properties | awk -F '=' '{print $2}' | tr -d '[:space:]')" >> $GITHUB_ENV

  #    - name: Sign APK
  #      uses: r0adkll/sign-android-release@v1
  #      with:
  #        releaseDirectory: app/build/outputs/apk/release
  #        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
  #        alias: ${{ secrets.ALIAS }}
  #        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
  #        keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Release APK to GitHub Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.WG_VERSION_NAME }}
          draft: false
          prerelease: false
          files: ui/build/outputs/apk/release/ui-release-unsigned.apk
